@content = application/json
@username = Miouss
@password = c
@email = test@gmail.com
@newPassword = password_changed

### Create account
POST http://localhost:3001/api/account HTTP/1.1
content-type: {{content}}

{
    "username": "{{username}}",
    "password": "{{password}}",
    "email": "{{email}}"
}

### Confirm account
GET http://localhost:3001/api/account?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pb3VzcyIsImlhdCI6MTY4NTYxNDA1NywiZXhwIjoxNjg1NjE0NjU3fQ.L1c8ubOuucpQDB1Cpqbsia5wbMxZIJ-LkI75zyKM2AA

### Change password
PATCH http://localhost:3001/api/account/password HTTP/1.1
content-type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}",
    "newPassword": "{{newPassword}}"
}


### Delete account
DELETE http://localhost:3001/api/account HTTP/1.1
content-type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

